development:
  adapter: mysql2
  encoding: utf8
  database: x_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: x_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: x_production
  pool: 5
  username: root
  password:
  host: ''
